
[mypy]
warn_unused_configs = True
files = src/pint
# 3.8 causes a problem with some versions of matplotlib
python_version = 3.9
warn_unreachable = True
warn_return_any = True
local_partial_types = True

[mypy-pint.templates.*]
ignore_errors = True

[mypy-pint.derived_quantities]
ignore_errors = True

[mypy-pint.observatory.*]
ignore_errors = True

[mypy-pint.models.stand_alone_psr_binaries.*]
ignore_errors = True

[mypy-pint.models.timing_model]
ignore_errors = True

[mypy-pint.models.pulsar_binary]
ignore_errors = True

[mypy-pint.fitter]
ignore_errors = True

[mypy-pint.polycos]
ignore_errors = True

[mypy-pint.output.publish]
ignore_errors = True

[mypy-pint.gridutils]
ignore_errors = True

[mypy-pint.scripts.*]
ignore_errors = True

[mypy-pint.pintk.plk]
ignore_errors = True

[mypy-pint.extern.*]
ignore_errors = True

[mypy-astropy.*]
ignore_missing_imports = True

[mypy-erfa]
ignore_missing_imports = True

[mypy-emcee]
ignore_missing_imports = True

[mypy-jplephem]
ignore_missing_imports = True

[mypy-numdifftools]
ignore_missing_imports = True

[mypy-pylab]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-uncertainties]
ignore_missing_imports = True

